"""
This type stub file was generated by pyright.
"""

import click

@click.command("main")
@click.option("--ingest_dir", help="""Path to directory containing files for an ingest. These will be generated by the Translator-Ingest repo.
    Looks for files ending with
        --"nodes.jsonl"
        --"edges.jsonl"
        --"normalized_nodes.jsonl"
        --"normalized_edges.jsonl"
      """)
def main(ingest_dir: str): # -> None:
    ...

if __name__ == "__main__":
    ...
