"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Iterable, Optional
from .kgxval_types import INGEST_MAP

def findNodeFile(ingest_dir: str | Path, find_normalized: bool = ...) -> Optional[str]:
    ...

def findEdgeFile(ingest_dir: str | Path, find_normalized: bool = ...) -> Optional[str]:
    ...

def expandCategories(cats: tuple[str, ...]) -> set[str]:
    ...

class Ingest:
    def __init__(self, ingest_name: str, node_path: Path, edge_path: Optional[Path], norm_status: str = ...) -> None:
        ...
    
    def iter_nodes(self) -> Iterable[dict[str, Any]]:
        ...
    
    manadatory_keys = ...
    def iter_edges(self, attach_original_json: bool = ..., validate: bool = ...) -> Iterable[dict[str, Any]]:
        ...
    
    def get_node_id_to_equiv_ids(self, node_id: str) -> tuple[str, ...]:
        ...
    
    def get_node_to_category_dict(self) -> dict[str, tuple[str, ...]]:
        ...
    
    def get_node_id_category(self, node_id: str): # -> tuple[str, ...]:
        ...
    
    def get_node_to_name_dict(self): # -> dict[str, str]:
        ...
    
    def get_node_id_name(self, node_id: str): # -> str:
        """Get the name of a node based on it's ID (the name provided in the node KGX file)."""
        ...
    


def makeNotNormalizedIngest(source_name: str, source_dir: str) -> list[Ingest]:
    ...

def makeNormalizedIngest(source_name: str, source_dir: str) -> list[Ingest]:
    ...

def makeIngestObjsFromTopLevelDir(top_lvl_dir_path: Path | str) -> list[Ingest]:
    ...

def makeIngestObjsDict(top_level_dir_path: Path | str) -> INGEST_MAP:
    ...

