"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from .Ingest import Ingest

if TYPE_CHECKING:
    ...
KGX_NODE = dict[str, Any]
KGX_EDGE = dict[str, Any]
KGX_SUMM = dict[str, Any]
INGEST_MAP = dict[str, dict[str, "Ingest"]]
SPQO_TUPLE = tuple[str, str, str, str]
PD_SUMM_ROW = dict[str, float | int | str | SPQO_TUPLE]
