from datetime import datetime
from typing import Optional
import click
from pathlib import Path

import pandas as pd
from kgxval.dir.KGXSummarizer import KGXSummarizer
from kgxval.dir.Ingest import makeIngestObjsDict, makeIngestObjsFromTopLevelDir, makeNormalizedIngest, makeNotNormalizedIngest
from kgxval.dir.kgxval_types import INGEST_MAP
from kgxval.dir.pandas_outputter import ExcelDFFlags, makeExcelSheetForSource, makeSummaryDF
import os
from tqdm import tqdm

@click.command("one_source")
@click.option(
    "--ingest_dir",
    help="""Path to directory containing files for an ingest. These will be generated by the Translator-Ingest repo.
    Looks for files ending with
        --"nodes.jsonl"
        --"edges.jsonl"
        --"normalized_nodes.jsonl"
        --"normalized_edges.jsonl"
      """,
)
@click.option(
    "--output_dir",
    help="""Where we should output the XLSX files to."""
)
def one_source(ingest_dir:str,output_dir:str):
    print(ingest_dir)
    source_name = Path(ingest_dir).stem
    ingests = makeNotNormalizedIngest(source_name, ingest_dir)
    ingests += makeNormalizedIngest(source_name, ingest_dir)
    ingest_dict:INGEST_MAP = {}
    for ingest_obj in ingests:
        source_name, norm = (ingest_obj.ingest_name, ingest_obj.norm_status)
        ingest_dict[source_name][norm] = ingest_obj

    excel_sheet_flags = ExcelDFFlags(unnorm_samp=True, unnorm_summ=True)

    datestr = datetime.now().strftime("%b-%d-%y")  # ex. Feb-16-2026

    makeExcelSheetForSource(
        ingest_dict=ingest_dict,
        source_name=source_name,
        hp_cats=[],
        outpath=f"{output_dir}/{source_name}_{datestr}_summary.xlsx",
        pbar=None,
        config=excel_sheet_flags,
    )

@click.command("many_sources")
@click.argument(
    "top_level_dir",
    type=str,
)
@click.option(
    "--task_number",
    help="""This is an integer {0,1,...,n-1} (where n is the number of unique data sources in top_level_dir). This should usually be $SLURM_ARRAY_TASK_ID.
    If this is not set, will just run through all sources sequentially.""",
    type=int,
    default=None,
)
def many_sources(top_level_dir:str,task_number:Optional[int]):
    ingest_dict = makeIngestObjsDict(top_level_dir)
    hp_cats:tuple[str,...] = tuple([
        "gene or gene product",
        "disease or phenotypic feature",
        "chemical entity",
    ])

    datestr = datetime.now().strftime("%b-%d-%y")  # ex. Feb-16-2026
    outdir = f"data/output/{datestr}"
    os.makedirs(outdir, exist_ok=True)

    pbar:tqdm[str] = tqdm(sorted(list(ingest_dict)))
    #task_number = os.getenv("SLURM_ARRAY_TASK_ID")
    #print(f"\n$SLURM_ARRAY_TASK_ID is {slurm_job}\n")
    for i, source_name in enumerate(pbar):
        #If $SLURM_ARRAY_TASK_ID is set; we're subdividing the task between multiple different compute cores.
        #This code will skip/continue past all datasets except dataset i==$SLURM_ARRAY_TASK_ID
        if(task_number is not None):
            if(i==int(task_number)):
                print(f"\n === Executing build for source {i} - {source_name} === \n")
            else:continue
        pbar.set_description(source_name)
        excel_sheet_flags = ExcelDFFlags(unnorm_samp=False, unnorm_summ=False)

        makeExcelSheetForSource(
            ingest_dict=ingest_dict,
            source_name=source_name,
            hp_cats=hp_cats,
            outpath=f"{outdir}/{source_name}_{datestr}_summary.xlsx",
            pbar=pbar,
            config=excel_sheet_flags,
        )

@click.command("merge_sources_together")
@click.argument(
    "top_level_dir",
    type=str,
)
def merge_sources_together(top_level_dir:str):
    ingest_dict = makeIngestObjsDict(top_level_dir)

    datestr = datetime.now().strftime("%b-%d-%y")  # ex. Feb-16-2026
    outdir = f"data/output/{datestr}"
    os.makedirs(outdir, exist_ok=True)

    for x in list(ingest_dict):
        if("translator_kg" in x):
            ingest_dict.pop(x)

    pbar:tqdm[str] = tqdm(sorted(list(ingest_dict)))
    
    first_key = sorted(list(ingest_dict))[0]
    first_ingest_obj = ingest_dict[first_key]["normalized"]
    norm_summ = KGXSummarizer.initWithIngestObj(first_ingest_obj, [])
    for i, source_name in enumerate(pbar):
        pbar.set_description(source_name)
        ingest_obj = ingest_dict[source_name]["normalized"]
        norm_summ.add_summarize_edges_for_iter(ingest_obj.iter_edges(),ingest_obj,source_name)
    writer = pd.ExcelWriter(f"data/merged_output/merged_summary_{datestr}.xlsx") 
    norm_df = makeSummaryDF(norm_summ.get_pd_rows(), rollup=False)
    norm_df.to_excel(
            writer, sheet_name=f"normalized_merge_summary", index=False
    )
    writer.close()

if __name__ == "__main__":
   #main()
   pass