[project]
name = "kgxval"
version = "0.0.0"
description = "Checks the predicates from biolink data translator."
requires-python = ">=3.13,<4"
authors = [
    { name="Daniel Korn", email="daniel_korn@med.unc.edu"}
]
readme = "README.md"
license = "BSD-3-Clause"

dependencies = [
    "bmt>=1.4.8",
    "pandas",
    "pandas-stubs", #Makes the type checker happy.
    "pydantic",
    "xlsxwriter>=3.0.3",
    "pyxlsb>=1.0.10",
    "odfpy>=1.4.1",
    "types-tqdm",
    "click",
    "openpyxl",
]

#[project.optional-dependencies]
[dependency-groups]
dev = [
    "tqdm",
    "pytest",
    "dotenv",
    "ruff>=0.15.8",
    "black>=26.3.1",
    "codespell>=2.4.2",
]

[tool.uv]
default-groups = ["dev"]
package = true

[tool.uv.sources]
bmt = { git = "https://github.com/biolink/biolink-model-toolkit.git", rev = "master" }

[tool.pytest.ini_options]
pythonpath = "src"

[tool.ruff]
line-length = 120
lint.extend-ignore = [

]
lint.exclude = []
# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
# Select or ignore from https://beta.ruff.rs/docs/rules/
lint.select = [
    "B",  # bugbear
    "D",  # pydocstyle
    "E",  # pycodestyle errors
    "F",  # Pyflakes
    "I",  # isort 
    "S",  # flake8-bandit
    "W",  # Warning
    "ARG",
    "C90",
]

lint.unfixable = []
target-version = "py310"

lint.mccabe.max-complexity = 10


[project.scripts]
ingest_summary = "kgxval.cli:ingest_summary"
merge_sources_together = "kgxval.cli:merge_sources_together"
norm_errors = "kgxval.cli:find_normalization_cat_errors"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"