[project]
name = "kgxval"
version = "0.0.0"
description = "Checks the predicates from biolink data translator."
requires-python = ">=3.13,<4"
authors = [
    { name="Daniel Korn", email="daniel_korn@med.unc.edu"}
]
readme = "README.md"
license = "BSD-3-Clause"

dependencies = [
    "bmt",
    "pandas",
    "pandas-stubs", #Makes the type checker happy.
    "pydantic",
    "xlsxwriter>=3.0.3",
    "pyxlsb>=1.0.10",
    "odfpy>=1.4.1",
]

#[project.optional-dependencies]
[dependency-groups]
dev = [
    "tqdm",
    "pytest",
    "dotenv",
    "ruff>=0.15.8",
    "black>=26.3.1",
    "codespell>=2.4.2",
]

[tool.uv]
default-groups = ["dev"]
package = true

#[tool.uv.sources]
#bmt = { git = "https://github.com/biolink/biolink-model-toolkit.git", rev = "master" }

[tool.pytest.ini_options]
pythonpath = "src"
