"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from pydantic import BaseModel
from lib.Ingest import Ingest

class PREFIX_ERR(BaseModel, frozen=True):
    source: str
    norm_status: str
    prefix: str
    cat: str
    ...


def getNodeStructuralErrors(ingest: Ingest, fail_on_invalid: bool) -> list[PREFIX_ERR]:
    ...

def getUniqueNodePrefixCats(ingest: Ingest) -> set[tuple[str, str]]:
    ...

def validateNodePrefixesForIngest(ingest: Ingest, fail_on_invalid: bool = ...) -> list[PREFIX_ERR]:
    ...

def writeErrorsToFile(error_dict: dict[tuple[str, str], set[str]], output_path: Path): # -> None:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
