"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Iterable, Optional
from bmt import Toolkit
from pydantic import BaseModel
from ..Ingest import Ingest
from .kgxval_types import KGX_EDGE, KGX_SUMM, PD_SUMM_ROW, SPQO_TUPLE

NONPROPERTY_KEYS: frozenset[str] = ...
MATT_QUALIFIER_ORDER: tuple[str, ...] = ...
def makePipeJoinedStringIfList(str_or_list: str | list[str]) -> str:
    ...

def cleanPrefixesFromDictVals(dict: dict[str, Any]) -> dict[str, Any]:
    ...

def orderQualifiersForMatt(qualifiers: Iterable[str]) -> list[str]:
    ...

class SPQO(BaseModel, frozen=True):
    """A class representing a unique tuple of Subject, Predicate, Qualifier, and Object.
    We assume that the set of node categories for subject and object have been collapsed
    down to a single category.
    """
    scat: str
    pred: str
    q_pred: str
    ocat: str
    def makeTuple(self) -> SPQO_TUPLE:
        ...
    


class SPQOStats:
    spqo: SPQO
    ingest: Ingest
    cnt: int
    at_set: set[str]
    kl_set: set[str]
    prop_set: set[str]
    pks_set: set[str]
    sks_set: set[str]
    suppds_set: set[str]
    aks_set: set[str]
    qualifier_vals: dict[str, set[str]]
    act_scats: set[str]
    act_ocats: set[str]
    pub_cnts: list[int]
    evidence_cnts: list[int]
    def __init__(self, spqo: SPQO, ingest: Ingest) -> None:
        ...
    
    @staticmethod
    def testQualifier(potential_qual: str) -> bool:
        """Check to see if a key is a qualifier"""
        ...
    
    @staticmethod
    def testPopulatedVal(val: Optional[str | int]) -> bool:
        """This looks at the field that's attached to a key in an edge dict. These fields can be left null in a few weird ways.
        We just check if it isn't Null and also that it isn't an empty string.
        """
        ...
    
    def incrementStats(self, edge: KGX_EDGE): # -> None:
        ...
    
    def makePdOutputRow(self, kgx_infores: str, normalized: str, total_edge_cnt: int) -> PD_SUMM_ROW:
        ...
    


class KGXSummarizer(Ingest):
    tk: Toolkit
    high_priority_desc_dict: dict[str, set[str]]
    blink_class_to_depth: dict[str, int]
    spqo_to_stats: dict[SPQO, SPQOStats]
    total_edge_cnt: int
    summarize_edges_ran: bool
    def __init__(self, ingest_name: str, node_path: Path, edge_path: Optional[Path], norm_status: str, high_priority_node_cats: Iterable[str]) -> None:
        ...
    
    @classmethod
    def initWithIngestObj(cls, ingest_obj: Ingest, high_priority_node_cats: Iterable[str]): # -> Self:
        ...
    
    def summarize_edges(self) -> list[KGX_SUMM]:
        ...
    
    def sample_edges(self) -> list[KGX_EDGE]:
        ...
    
    def get_pd_rows(self) -> list[PD_SUMM_ROW]:
        ...
    


