"""
This type stub file was generated by pyright.
"""

import csv
import json
import logging
from pathlib import Path
from typing import Any, Iterable, Optional
from .kgxval_types import KGX_EDGE, KGX_NODE

def JSONLDictGen(file_loc: Optional[Path], attach_original_json: bool = ...) -> Iterable[KGX_NODE | KGX_EDGE]:
    ...

def TSVDictGen(file_loc: Optional[Path], _: bool = ...) -> Iterable[KGX_NODE | KGX_EDGE]:
    ...

if __name__ == "__main__":
    ...
