"""
This type stub file was generated by pyright.
"""

import csv
import functools
from collections import defaultdict
from typing import Iterable, Optional
from bmt import Toolkit
from linkml_runtime.linkml_model.meta import ClassDefinition, SlotDefinition
from pydantic import BaseModel
from ..Ingest import Ingest, expandCategories

tk: Optional[Toolkit] = ...
def get_toolkit() -> Toolkit:
    ...

class SOPC(BaseModel, frozen=True):
    """This class represents the most core information for validating an edge predicate and categories.
    We only need to know what the subject categories were, what the object categories were, the
    predicate, and all of the edge categories.
    """
    node_sub_cats: tuple[str, ...]
    node_obj_cats: tuple[str, ...]
    predicate: str
    edge_cats: tuple[str, ...]
    def to_csv_list(self): # -> list[str]:
        ...
    


def writeSOPCsToFile(ingest: Ingest, outpath: str): # -> None:
    ...

class SPOCValidationError(BaseModel, frozen=True):
    pred: str
    error: str
    valid_cats: list[str]
    actual_cats: tuple[str, ...]
    ingest_name: str
    normalized: str
    def to_csv_list(self): # -> list[str]:
        ...
    


@functools.cache
def getSubRange(pred: Optional[str]) -> Optional[str]:
    ...

@functools.cache
def getObjRange(pred: Optional[str]) -> Optional[str]:
    ...

def findSubObjErrorsForIngest(ingest: Ingest) -> list[SPOCValidationError]:
    ...

def validationErrorsToFile(spoc_errors: list[SPOCValidationError], outfile: str): # -> None:
    ...

