from datetime import datetime
import click
from pathlib import Path
from lib.Ingest import makeIngestObjsFromTopLevelDir, makeNormalizedIngest, makeNotNormalizedIngest
from lib.kgxval_types import INGEST_MAP
from lib.pandas_outputter import ExcelDFFlags, makeExcelSheetForSource
#from lib.pandas_outputter import ExcelDFFlags, makeExcelSheetForSource

@click.command("main")
@click.option(
    "--ingest_dir",
    help="""Path to directory containing files for an ingest. These will be generated by the Translator-Ingest repo.
    Looks for files ending with
        --"nodes.jsonl"
        --"edges.jsonl"
        --"normalized_nodes.jsonl"
        --"normalized_edges.jsonl"
      """,
)
@click.option(
    "--output_dir",
    help="""Where we should output the XLSX files to.""",
    default="data/output"
)
def main(ingest_dir:str,output_dir:str):
    print(ingest_dir)
    source_name = Path(ingest_dir).stem
    ingests = makeNotNormalizedIngest(source_name, ingest_dir)
    ingests += makeNormalizedIngest(source_name, ingest_dir)
    ingest_dict:INGEST_MAP = {source_name:{}}
    for ingest_obj in ingests:
        source_name, norm = (ingest_obj.ingest_name, ingest_obj.norm_status)
        ingest_dict[source_name][norm] = ingest_obj

    datestr = datetime.now().strftime("%b-%d-%y")  # ex. Feb-16-2026

    excel_sheet_flags = ExcelDFFlags(unnorm_samp=True, unnorm_summ=True)
    makeExcelSheetForSource(
        ingest_dict=ingest_dict,
        source_name=source_name,
        hp_cats=[],
        outpath=f"{output_dir}/{source_name}_{datestr}_summary.xlsx",
        pbar=None,
        config=excel_sheet_flags,
    )

if __name__ == "__main__":
    main()